"""Headless Unreal Engine adapter — RenderSpec v2 → cinematic previz → MP4.

Unreal Engine 5 is the **cinematic / real-time tier** of the MelosViz
pipeline. Where ComfyUI and C4D produce frames offline, UE lets a
director re-render in seconds with Movie Render Queue (``RenderMovie`` /
``MoviePipeline``) and Sequencer — perfect for:

* Festival-grade 3-D real-time previz
* Live VJ / projection-mapping (see also ``melosviz.runtime.touchdesigner``)
* Nanite / Lumen scenes that *cannot* be done in ComfyUI or Blender
* MetaHuman performers (UE's biggest differentiator)

How this adapter drives UE
--------------------------
We *don't* re-implement rendering inside Python — UE does that. Instead we
write a Python ``ue``-aware driver script (UE5's editor Python) and invoke
``UnrealEditor-Cmd.exe`` (Windows) / ``UnrealEditor-Cmd`` (Linux/Mac) with
``-run=pythonscript``. That script:

1. Loads (or creates) a Sequencer ``ULevelSequence``.
2. Drops in the scene's animated actors (or import an alembic / FBX asset
   path the orchestrator supplied).
3. Wires beat markers from the RenderSpec's timeline events into the
   sequence's event tracks.
4. Triggers ``MoviePipelineQueueEngineSubsystem`` to render the sequence
   to ``output_dir/<scene>.mp4``.

The Python driver script is shipped at ``backend/scripts/ue_render.py``
(generated by :func:`scaffold_driver`); override with
``MELOSVIZ_UE_DRIVER_SCRIPT`` to use your own.

Configuration (env vars)
------------------------
``MELOSVIZ_UE_BIN``            Path to ``UnrealEditor-Cmd`` (or
                               ``UnrealEditor.exe`` on Windows).
``MELOSVIZ_UE_PROJECT``        Path to the ``.uproject`` we drive.
``MELOSVIZ_UE_DRIVER_SCRIPT``  Path to the driver script (default
                               ``backend/scripts/ue_render.py``).
``MELOSVIZ_UE_TIMEOUT``        Wall-clock per-scene timeout, seconds
                               (default ``3600`` = 1 h).
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover
    from melosviz.analysis.models import RenderSpec

logger = logging.getLogger(__name__)

__all__ = [
    "UEAdapter",
    "UENotFoundError",
    "UERenderError",
    "is_unreal_available",
    "render_scene",
    "scaffold_driver",
]

# ---------------------------------------------------------------------------
# Constants / env vars
# ---------------------------------------------------------------------------

_UE_BIN_ENV = "MELOSVIZ_UE_BIN"
_UE_PROJECT_ENV = "MELOSVIZ_UE_PROJECT"
_UE_DRIVER_ENV = "MELOSVIZ_UE_DRIVER_SCRIPT"
_UE_TIMEOUT_ENV = "MELOSVIZ_UE_TIMEOUT"

DEFAULT_TIMEOUT_S = 3600

SCENE_TYPES: tuple[str, ...] = ("unreal_cinematic", "ue_cinematic")


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class UEError(RuntimeError):
    """Base class for any UE adapter failure."""


class UENotFoundError(UEError):
    """Neither the UE editor binary nor the project was located."""


class UERenderError(UEError):
    """UE exited non-zero, produced no frames, or the driver script raised."""


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------


def _ue_bin() -> str | None:
    p = os.environ.get(_UE_BIN_ENV)
    if p and Path(p).exists():
        return p
    on_path = shutil.which("UnrealEditor-Cmd") or shutil.which("UnrealEditor")
    return on_path


def _ue_project() -> Path | None:
    p = os.environ.get(_UE_PROJECT_ENV)
    return Path(p).expanduser().resolve() if p else None


def _ue_driver() -> Path:
    override = os.environ.get(_UE_DRIVER_ENV)
    if override:
        return Path(override).expanduser().resolve()
    here = Path(__file__).resolve()
    # backend/src/melosviz/render/unreal_adapter.py → ../../../scripts
    return (here.parent.parent.parent / "scripts" / "ue_render.py").resolve()


def _ue_timeout_s() -> int:
    raw = os.environ.get(_UE_TIMEOUT_ENV, str(DEFAULT_TIMEOUT_S))
    try:
        return max(60, int(raw))
    except ValueError:
        return DEFAULT_TIMEOUT_S


def is_unreal_available() -> bool:
    """True iff the UE binary AND a project file are reachable."""
    return _ue_bin() is not None and _ue_project() is not None


# ---------------------------------------------------------------------------
# Driver script generation
# ---------------------------------------------------------------------------


_DRIVER_TEMPLATE = '''\
"""Auto-generated UE Movie Render Queue driver for MelosViz.

Reads a MelosViz scene JSON from argv[1] and renders the corresponding
sequence to argv[2] via Unreal's MoviePipeline.

Edit / fork freely — MelosViz passes everything you need as JSON so this
script stays tiny.
"""
import json, sys, unreal

SCENE_PATH = sys.argv[1]
OUT_DIR    = sys.argv[2]

def main():
    with open(SCENE_PATH, "r", encoding="utf-8") as f:
        scene = json.load(f)
    asset   = scene.get("asset", "")     # /Game/Sequences/MySequence
    seq     = scene.get("sequence", asset) or asset
    width   = int(scene.get("width",  1280))
    height  = int(scene.get("height",  720))
    frames  = int(scene.get("frames", 240))
    fps     = float(scene.get("fps", 24))
    out_name = scene.get("name", "melosviz_scene")

    # 1. Open or create the sequence
    if seq and unreal.EditorAssetLibrary.does_asset_exist(seq):
        sequence = unreal.load_asset(seq)
    else:
        sequence = unreal.LevelSequenceEditorBlueprintLibrary.create_level_sequence_player(
            unreal.LevelSequence.get_default_object()
        ).get_sequence()
        if sequence is None:
            raise RuntimeError("UE: failed to create sequence")

    # 2. Beat markers → event track
    beats = scene.get("beats", [])
    if beats:
        track = sequence.add_master_track(unreal.MovieSceneEventTrack)
        for beat in beats:
            ms = unreal.FrameTime(beat.get("frame", 0))
            event = unreal.MovieSceneEvent()
            track.add_section_at_time(ms)

    # 3. Movie render queue
    queue = unreal.get_editor_subsystem(unreal.MoviePipelineQueueEngineSubsystem)
    job = queue.allocate_new_job()
    job.map = unreal.EditorLoadingAndSavingUtils.new_blank_map()
    job.sequence = unreal.SoftObjectPath(seq) if seq else unreal.SoftObjectPath()

    cfg = unreal.MoviePipelineMasterConfig()
    output = unreal.MoviePipelineOutputSetting()
    output.output_directory = unreal.DirectoryPath(OUT_DIR)
    output.file_name_format = out_name + "_$F.png"
    output.output_format = unreal.MoviePipelineOutputSetting.IMAGE_PNG
    cfg.output_setting = output

    render = unreal.MoviePipelineDeferredPassBase()
    cfg.add_setting(render)

    job.set_configuration(cfg)
    queue.add_job(job)
    queue.render_next_job()

    print("UE_RENDER_OK", out_name)

if __name__ == "__main__":
    main()
'''


def scaffold_driver(path: Path | str) -> Path:
    """Write the default UE driver script to ``path`` (idempotent)."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if not p.exists():
        p.write_text(_DRIVER_TEMPLATE, encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_scene(scene: dict[str, Any], *, output_dir: Path | str,
                 project: Path | None = None,
                 driver: Path | None = None) -> list[Path]:
    """Render one UE scene; returns list of output frame paths."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    bin_ = _ue_bin()
    if bin_ is None:
        raise UENotFoundError(
            "UnrealEditor-Cmd not found on $PATH. "
            f"Set ${_UE_BIN_ENV} to your UE install."
        )
    proj = project or _ue_project()
    if proj is None:
        raise UENotFoundError(
            "No UE project (.uproject) given. "
            f"Set ${_UE_PROJECT_ENV} or pass project=..."
        )
    driver_path = scaffold_driver(driver or _ue_driver())

    scene_payload = out / "scene.json"
    scene_payload.write_text(json.dumps(scene, indent=2), encoding="utf-8")

    cmd = [
        bin_, str(proj),
        "-run=pythonscript",
        f"-script={driver_path}",
        # The driver reads scene + out via argv
        f'"{scene_payload}"',
        f'"{out}"',
        "-unattended", "-nopause", "-nosplash",
    ]
    timeout = _ue_timeout_s()
    logger.info("UE: invoking %s", " ".join(cmd))
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired as exc:
        raise UERenderError(f"UE render timed out after {timeout}s") from exc
    if proc.returncode != 0 or "UE_RENDER_OK" not in proc.stdout:
        raise UERenderError(
            f"UE render failed (rc={proc.returncode}): "
            f"{proc.stderr.strip() or proc.stdout.strip()[-2000:]}"
        )
    frames = sorted(out.glob("*.png"))
    if not frames:
        raise UERenderError(f"UE produced no frames under {out}")
    return frames


# ---------------------------------------------------------------------------
# Adapter (conductor integration)
# ---------------------------------------------------------------------------


class UEAdapter:
    """Conductor-compatible adapter for Unreal Engine."""

    scene_type: str = "unreal_cinematic"

    def render(self, render_spec: Any, *, output_path: Any = None,
               **kwargs: Any) -> list[Path]:
        out_dir = Path(str(output_path)) if output_path is not None else Path(
            "/tmp/melosviz-ue"
        )
        out_dir.mkdir(parents=True, exist_ok=True)

        # ---- Offline mode: write job-spec JSON, do NOT invoke UE -----------
        if os.environ.get("MELOSVIZ_COMFYUI_OFFLINE") == "1":
            scenes = _extract_scenes(render_spec, scene_type=self.scene_type)
            plan_path = out_dir / "ue_render_plan.json"
            spec_dict: dict[str, Any] = (
                render_spec.model_dump()
                if hasattr(render_spec, "model_dump")
                else (render_spec if isinstance(render_spec, dict) else {})
            )
            plan = {
                "renderer": "unreal_engine",
                "mode": "offline",
                "reason": "MELOSVIZ_COMFYUI_OFFLINE=1 — UE not invoked",
                "output_dir": str(out_dir),
                "n_scenes": len(scenes),
                "spec_summary": {
                    "duration_s": (spec_dict.get("metadata") or {}).get("duration"),
                    "n_segments": len(spec_dict.get("scene_segments") or []),
                    "palette": spec_dict.get("palette", []),
                },
                "render_params": {
                    "project": str(kwargs.get("project") or _ue_project() or ""),
                    "timeout_s": _ue_timeout_s(),
                },
                "driver_script_path": "scene_NNN/_ue_render.py",
                "next_steps": [
                    "Install Unreal Engine 5.x and ensure UnrealEditor-Cmd is on PATH.",
                    "Re-run with MELOSVIZ_COMFYUI_OFFLINE unset (or =0).",
                    f"Or: set ${_UE_BIN_ENV} / ${_UE_PROJECT_ENV} and re-run.",
                ],
            }
            plan_path.write_text(json.dumps(plan, indent=2, default=str))
            # Also scaffold the per-scene UE python driver scripts so the
            # operator can hand them to a UE render farm.
            for i, scene in enumerate(scenes):
                scene_out = out_dir / f"scene_{i:03d}"
                scene_out.mkdir(parents=True, exist_ok=True)
                (scene_out / "_ue_render.py").write_text(_DRIVER_TEMPLATE, encoding="utf-8")
                (scene_out / "scene.json").write_text(
                    json.dumps(scene, indent=2), encoding="utf-8"
                )
            logger.info("UEAdapter: offline mode → wrote %s", plan_path)
            return [plan_path]

        scenes = _extract_scenes(render_spec, scene_type=self.scene_type)
        if not scenes:
            logger.warning(
                "UEAdapter: no scenes of type=%r in spec; nothing to render",
                self.scene_type,
            )
            return []

        results: list[Path] = []
        for i, scene in enumerate(scenes):
            scene_out = out_dir / f"scene_{i:03d}"
            scene_out.mkdir(parents=True, exist_ok=True)
            try:
                frames = render_scene(
                    scene, output_dir=scene_out,
                    project=kwargs.get("project"),
                    driver=kwargs.get("driver"),
                )
            except UEError:
                raise
            results.extend(frames)
        return results


def _extract_scenes(render_spec: Any, *, scene_type: str) -> list[dict]:
    if hasattr(render_spec, "model_dump"):
        data = render_spec.model_dump()
    elif isinstance(render_spec, dict):
        data = render_spec
    else:
        return []
    scenes = data.get("scenes") or data.get("scene_segments") or []
    out: list[dict] = []
    for s in scenes:
        if isinstance(s, dict) and s.get("scene_type") in SCENE_TYPES:
            out.append(s)
    return out
