"""Stub C4D driver script (generated by C4DAdapter at runtime).

This is the placeholder script the C4DAdapter writes for each scene. When
the real c4dpy is unavailable (i.e., the runtime is offline mode), this
script is what would be invoked by the c4d-stub HTTP server above.

Real C4D pipeline: replace this file with the c4dpy equivalent
(``import c4d; doc = c4d.documents.LoadDocument(...); c4d.documents.SaveDocument(...)``)
and point MELOSVIZ_C4D_REAL_C4DPY at the c4dpy binary. Everything else
stays identical.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def main() -> int:
    plan_path = Path(os.getenv("MELOSVIZ_C4D_PLAN_PATH", sys.argv[1] if len(sys.argv) > 1 else "c4d_render_plan.json"))
    plan = json.loads(plan_path.read_text())

    output_path = Path(plan["output_path"])
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # In real c4dpy, we'd do:
    #     import c4d
    #     doc = c4d.documents.LoadDocument(plan["scene_path"])
    #     rdata = doc.GetActiveRenderData()
    #     rdata[c4d.RDATA_FRAMESEQUENCE] = c4d.RDATA_FRAMESEQUENCE_MANUAL
    #     rdata[c4d.RDATA_FRAMEFROM] = plan["frame_from"]
    #     rdata[c4d.RDATA_FRAMETO]   = plan["frame_to"]
    #     c4d.documents.SaveDocument(doc, str(output_path), c4d.SAVEDOCUMENTFLAGS_DONTADDTORECENT)
    #     c4d.documents.RenderDocument(doc, rdata)
    # Stub: emit a sidecar JSON so the pipeline can ingest.

    sidecar = {
        "scene_name": plan.get("scene_name"),
        "frames": plan.get("frames"),
        "fps": plan.get("fps"),
        "width": plan.get("width"),
        "height": plan.get("height"),
        "stub": True,
        "format": "exr",
    }
    output_path.with_suffix(".json").write_text(json.dumps(sidecar, indent=2))
    output_path.write_text("")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
