"""TD-side bootstrap script renderer.

When pasted into a TD Text DAT and executed *inside TouchDesigner*, the
output of :func:`render_bootstrap_script` reads ``network_spec.json`` from
the same directory and calls ``td.op()`` APIs to construct the live node
graph.

This module runs **outside** TD (in the MelosViz Python process) and only
renders the bootstrap script as a string.  TD itself is not required to be
installed here.

Architecture
------------
The rendered script follows TD's Python scripting conventions:
* ``op()`` / ``parent()`` — operator access
* ``create()`` — create a new operator inside a COMP
* ``par.<name>`` — set a parameter

The script structure:

1. Load ``network_spec.json`` from the same directory as the script.
2. For each group in the network spec, locate (or create) a Base COMP
   named after the group under ``/project1``.
3. For each operator node in the group, create the operator by ``op_type``
   and set params from the JSON.
4. Wire ``wires_from`` connections using ``op.inputConnectors[0].connect()``.
"""

from __future__ import annotations

from melosviz.runtime.touchdesigner.generator import NetworkSpec

__all__ = ["render_bootstrap_script"]

# ---------------------------------------------------------------------------
# Script template
# ---------------------------------------------------------------------------

_BOOTSTRAP_HEADER = '''\
"""MelosViz TouchDesigner bootstrap — auto-generated, do not edit.

Run inside TouchDesigner:  textDAT.run()  or paste into a Text DAT and
press Ctrl+R.  Requires network_spec.json in the same directory.

Generated by melosviz.runtime.touchdesigner.bootstrap.
"""
import json
import os

_DIR = os.path.dirname(os.path.abspath(__file__) if "__file__" in dir() else ".")
_SPEC_PATH = os.path.join(_DIR, "network_spec.json")

with open(_SPEC_PATH) as _f:
    _spec = json.load(_f)

_root = op("/project1")

def _get_or_create_comp(parent_comp, name: str):
    """Return existing child COMP or create a Base COMP."""
    child = parent_comp.findChildren(name=name, maxDepth=1)
    if child:
        return child[0]
    return parent_comp.create(baseCOMP, name)

def _set_params(node_op, params: dict):
    for k, v in params.items():
        try:
            setattr(node_op.par, k, v)
        except Exception as exc:
            print(f"[melosviz] Warning: could not set {node_op.name}.par.{k} = {v!r}: {exc}")

def _wire(group_comp, node_op, wires_from: list):
    for wire_ref in wires_from:
        parts = wire_ref.split("/")
        src_group_name = parts[0] if len(parts) == 2 else None
        src_op_name = parts[-1]
        if src_group_name:
            src_group = _root.findChildren(name=src_group_name, maxDepth=1)
            src_comp = src_group[0] if src_group else None
        else:
            src_comp = group_comp
        if src_comp:
            src_op = src_comp.findChildren(name=src_op_name, maxDepth=1)
            if src_op:
                try:
                    node_op.inputConnectors[0].connect(src_op[0])
                except Exception as exc:
                    print(f"[melosviz] Warning: wire {wire_ref} → {node_op.name} failed: {exc}")

# Build / update node graph from spec
for group_spec in _spec["groups"]:
    group_name = group_spec["name"]
    group_comp = _get_or_create_comp(_root, group_name)

    for op_spec in group_spec["operators"]:
        op_type_name = op_spec["op_type"]
        op_name = op_spec["name"]
        params = op_spec.get("params", {})
        wires_from = op_spec.get("wires_from", [])

        # Resolve TD op class by name (TD provides globals for each op class)
        op_class = globals().get(op_type_name)
        if op_class is None:
            print(f"[melosviz] Unknown op type: {op_type_name!r} — creating baseCOMP placeholder")
            op_class = baseCOMP

        existing = group_comp.findChildren(name=op_name, maxDepth=1)
        if existing:
            node_op = existing[0]
        else:
            node_op = group_comp.create(op_class, op_name)

        _set_params(node_op, params)
        _wire(group_comp, node_op, wires_from)

print("[melosviz] TD bootstrap complete — node graph constructed from network_spec.json")
'''


def render_bootstrap_script(network: NetworkSpec) -> str:
    """Render the TD-side bootstrap Python script.

    The returned string is a self-contained Python script that, when run
    *inside* TouchDesigner, builds the operator graph described by
    ``network``.

    Args:
        network: The :class:`~melosviz.runtime.touchdesigner.generator.NetworkSpec`
            that this script will reconstruct inside TD.

    Returns:
        The bootstrap script as a string.  Write it to a ``.py`` file
        alongside ``network_spec.json``.
    """
    # The script is static (reads the JSON at runtime inside TD) — the
    # network parameter is accepted for future per-spec customisation.
    _ = network  # reserved
    return _BOOTSTRAP_HEADER
